#' Generate data with Beta(a, b) distribution or Cauchy(l, s) distribution with Acceptance-rejection method.
#'
#' \code{rBC} use Acceptance-rejection method to generate data and then can use \code{CVM.test} to test data with the sample generated
#' by \code{rbeta} and \code{rcauchy}.
#' @export
#' @importFrom stats rbeta
#' @importFrom stats rcauchy
#' @importFrom stats runif
#' @importFrom stats rnorm
#' @importFrom stats dnorm
#' @importFrom stats dbeta
#' @importFrom stats dcauchy
#' @param n the size of sample.
#' @param a the first argument of Beta distribution or the location of Cauchy distribution.
#' @param b the second argument of Beta distribution or the scale of Cauchy distribution.
#' @param type the type of distribution, \emph{Beta} or \emph{Cauchy}.
#' @param p.value logical; FALSE is default. If TRUE, show the p-value of Cramer-von Mises test between samples generated by \code{rBC} and \code{rbeta} or \code{rcauchy}.
#' @return a numerical vector and p-value if TRUE.
#' @seealso \code{\link{CVM.test}}.
#' @examples
#'
#' \dontrun{
#' ## a sample with Beta(2, 3) and no p-value.
#' rBC(2, 3, type = "Beta")
#'
#' ## a sample with Cauchy(0, 1) and return p-value at the same time.
#' rBC(0, 1, type = "Cauchy", p = TRUE)
#' }
#'

rBC = function(n, a, b, type = NULL, p.value = FALSE) {
  x = numeric(n)
  i = 1
  if (type != "Beta" && type != "Cauchy") {
    cat("Error: no correct distribution!")
  }
  if (type == "Beta") {
    while (i <= n) {
      u = runif(1)
      y = runif(1)
      if (u < dbeta(y, a, b)/10) {
        x[i] = y
        i = i + 1
      }
    }
    if (p.value) {
      p = CVM.test(x, rbeta(n, a, b))$p.value
      return(list(x = x, p.value = p))
    }
    else return(x)
  }
  if (type == "Cauchy") {
    while (i <= n) {
      u = runif(1)
      y = rnorm(1, a, b)
      if (u < dcauchy(y, a, b)/10/dnorm(y, a, b)) {
        x[i] = y
        i = i + 1
      }
    }
    if (p.value) {
      p = CVM.test(x, rcauchy(n, a, b))$p.value
      return(list(x = x, p.value = p))
    }
    else return(x)
  }
}
